enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
included-patches = "'Ambient mode' 'Captions' 'Disable DRC audio' 'Disable Shorts resuming on startup' 'Force original audio' 'Hide ads' 'Hide player overlay buttons' 'Loop video' 'Remove background playback restrictions' 'Return YouTube Dislike' 'Spoof video streams' 'Swipe controls' 'Theme' 'Video ads' 'Video quality'"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
